/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_x402_x402_createWallet_parameter_0$schema = z.object({
  'label': z.string(),
  'privateKey': z.string().optional(),
})
const _deepseek_ai_dsh_x402_x402_createWallet_result$schema = z.object({
  'id': z.string(),
  'label': z.string(),
  'address': z.string(),
  'isCurrent': z.boolean(),
})
const _deepseek_ai_dsh_x402_x402_history_parameter_0$schema = z.union([z.undefined(), z.number()])
const _deepseek_ai_dsh_x402_x402_history_result$schema = z.array(z.object({
  'hash': z.string(),
  'from': z.string(),
  'to': z.string(),
  'amountUsdc': z.string(),
  'blockNumber': z.number(),
  'direction': z.union([z.literal("out"), z.literal("in")]),
}))
const _deepseek_ai_dsh_x402_x402_payments_result$schema = z.array(z.object({
  'id': z.string(),
  'url': z.string(),
  'amountUsdc': z.string(),
  'network': z.string(),
  'transaction': z.string().optional(),
  'status': z.union([z.literal("failed"), z.literal("settled")]),
  'time': z.number(),
}))
const _deepseek_ai_dsh_x402_x402_selectWallet_parameter_0$schema = z.string()
const _deepseek_ai_dsh_x402_x402_selectWallet_result$schema = z.object({
  'ok': z.literal(true),
})
const _deepseek_ai_dsh_x402_x402_send_parameter_0$schema = z.object({
  'to': z.string(),
  'amountUsdc': z.string(),
})
const _deepseek_ai_dsh_x402_x402_send_result$schema = z.object({
  'transaction': z.string(),
  'to': z.string(),
  'amountUsdc': z.string(),
  'status': z.literal("confirmed"),
})
const _deepseek_ai_dsh_x402_x402_wallet_result$schema = z.object({
  'configured': z.boolean(),
  'address': z.string().optional(),
  'usdcBalance': z.string().optional(),
  'network': z.string(),
  'label': z.string().optional(),
  'walletId': z.string().optional(),
})
const _deepseek_ai_dsh_x402_x402_wallets_result$schema = z.array(z.object({
  'id': z.string(),
  'label': z.string(),
  'address': z.string(),
  'isCurrent': z.boolean(),
}))

export const TYPERT = {
  package: '@deepseek-ai/dsh-x402',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-x402#x402/createWallet',
      service: 'x402',
      namespace: 'x402',
      method: 'createWallet',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-x402#x402/createWallet:request',
            schema: _deepseek_ai_dsh_x402_x402_createWallet_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-x402/types#X402WalletRecord',
        schema: _deepseek_ai_dsh_x402_x402_createWallet_result$schema,
      },
      sourceLocation: {"file":"packages/x402/x402/src/index.ts","line":273,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-x402#x402/history',
      service: 'x402',
      namespace: 'x402',
      method: 'history',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'limit',
          wire: 'limit',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-x402#x402/history:limit',
            schema: _deepseek_ai_dsh_x402_x402_history_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-x402#x402/history:result',
        schema: _deepseek_ai_dsh_x402_x402_history_result$schema,
      },
      sourceLocation: {"file":"packages/x402/x402/src/index.ts","line":332,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-x402#x402/payments',
      service: 'x402',
      namespace: 'x402',
      method: 'payments',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-x402#x402/payments:result',
        schema: _deepseek_ai_dsh_x402_x402_payments_result$schema,
      },
      sourceLocation: {"file":"packages/x402/x402/src/index.ts","line":342,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-x402#x402/selectWallet',
      service: 'x402',
      namespace: 'x402',
      method: 'selectWallet',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-x402#x402/selectWallet:id',
            schema: _deepseek_ai_dsh_x402_x402_selectWallet_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-x402#x402/selectWallet:result',
        schema: _deepseek_ai_dsh_x402_x402_selectWallet_result$schema,
      },
      sourceLocation: {"file":"packages/x402/x402/src/index.ts","line":305,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-x402#x402/send',
      service: 'x402',
      namespace: 'x402',
      method: 'send',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-x402#x402/send:request',
            schema: _deepseek_ai_dsh_x402_x402_send_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-x402/types#X402SendReceipt',
        schema: _deepseek_ai_dsh_x402_x402_send_result$schema,
      },
      sourceLocation: {"file":"packages/x402/x402/src/index.ts","line":318,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-x402#x402/wallet',
      service: 'x402',
      namespace: 'x402',
      method: 'wallet',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-x402/types#X402WalletState',
        schema: _deepseek_ai_dsh_x402_x402_wallet_result$schema,
      },
      sourceLocation: {"file":"packages/x402/x402/src/index.ts","line":237,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-x402#x402/wallets',
      service: 'x402',
      namespace: 'x402',
      method: 'wallets',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-x402#x402/wallets:result',
        schema: _deepseek_ai_dsh_x402_x402_wallets_result$schema,
      },
      sourceLocation: {"file":"packages/x402/x402/src/index.ts","line":259,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "The x402 payment capability: model tools, GUI remote, and wallet custody.",
        "summary": "The x402 payment capability: model tools, GUI remote, and wallet custody.",
        "tags": [],
        "jsDoc": "/** The x402 payment capability: model tools, GUI remote, and wallet custody. */",
        "key": "x402",
        "exportName": "X402Service",
        "members": [
          {
            "kind": "method",
            "name": "discover",
            "signature": "async discover(keyword?: string, network?: string): Promise<X402CatalogEntry[]>",
            "summary": "List live x402 APIs from the catalog, optionally filtered.",
            "jsDoc": "/**\n * List live x402 APIs from the catalog, optionally filtered.\n * @param keyword - substring filter against descriptions and URLs.\n * @param network - exact CAIP-2 network filter.\n * @returns at most the first 25 matching entries.\n */"
          },
          {
            "kind": "method",
            "name": "estimate",
            "signature": "async estimate(url: string, method?: string): Promise<X402EstimateResult>",
            "summary": "Probe one URL for its payment requirement without paying.",
            "jsDoc": "/**\n * Probe one URL for its payment requirement without paying.\n * @param url - resource to probe.\n * @param method - HTTP method for the probe; defaults to GET.\n * @returns free or one concrete requirement.\n */"
          },
          {
            "kind": "method",
            "name": "wallet",
            "signature": "@Remote('wallet') async wallet(): Promise<X402WalletState>",
            "summary": "Read the wallet snapshot: configured status, address, and USDC balance.",
            "jsDoc": "/**\n * Read the wallet snapshot: configured status, address, and USDC balance.\n * @returns wallet state; balance RPC failures surface loud.\n */"
          },
          {
            "kind": "method",
            "name": "wallets",
            "signature": "@Remote('wallets') async wallets(): Promise<X402WalletRecord[]>",
            "summary": "List every wallet in the registry, marking the selected one.",
            "jsDoc": "/**\n * List every wallet in the registry, marking the selected one.\n * @returns wallet records with the current selection flagged.\n */"
          },
          {
            "kind": "method",
            "name": "createWallet",
            "signature": "@Remote('createWallet') async createWallet(request: { label: string; privateKey?: string }): Promise<X402WalletRecord>",
            "summary": "Create a wallet: generate a fresh key, or import a provided one.",
            "jsDoc": "/**\n * Create a wallet: generate a fresh key, or import a provided one. The key\n * is written to the credentials store; the registry keeps only public data.\n * @param request - label and an optional private key to import.\n * @returns the new wallet record; it becomes the selection when it is the first.\n */"
          },
          {
            "kind": "method",
            "name": "selectWallet",
            "signature": "@Remote('selectWallet') async selectWallet(id: string): Promise<{ ok: true }>",
            "summary": "Make one wallet the selection used by payments and transfers.",
            "jsDoc": "/**\n * Make one wallet the selection used by payments and transfers.\n * @param id - durable wallet id from `wallets()`.\n * @returns confirmation once the selection is durably written.\n */"
          },
          {
            "kind": "method",
            "name": "send",
            "signature": "@Remote('send') async send(request: { to: string; amountUsdc: string }): Promise<X402SendReceipt>",
            "summary": "Send USDC from the current wallet to an address and wait for confirmation.",
            "jsDoc": "/**\n * Send USDC from the current wallet to an address and wait for confirmation.\n * @param request - recipient and human USDC amount.\n * @returns the confirmed transaction receipt.\n */"
          },
          {
            "kind": "method",
            "name": "history",
            "signature": "@Remote('history') async history(limit?: number): Promise<X402HistoryEntry[]>",
            "summary": "Read recent on-chain USDC transfers touching the current wallet.",
            "jsDoc": "/**\n * Read recent on-chain USDC transfers touching the current wallet.\n * @param limit - maximum entries; defaults to 50.\n * @returns transfers newest first with direction and human amounts.\n */"
          },
          {
            "kind": "method",
            "name": "payments",
            "signature": "@Remote('payments') payments(): Promise<X402PaymentRecord[]>",
            "summary": "Read the process-local payment history, newest first.",
            "jsDoc": "/**\n * Read the process-local payment history, newest first.\n * @returns the recorded settled and failed paid calls.\n */"
          },
          {
            "kind": "method",
            "name": "payForAgent",
            "signature": "async payForAgent(request: X402PayToolArgs & { agent: Agent; callId?: CallId; signal?: AbortSignal }): Promise<X402PaymentReceipt>",
            "summary": "Pay and call one x402 URL on behalf of an agent: probe, enforce the cap, ask the user for approval, sign, retry, and record the outcome.",
            "jsDoc": "/**\n * Pay and call one x402 URL on behalf of an agent: probe, enforce the cap,\n * ask the user for approval, sign, retry, and record the outcome.\n * @param request - URL, call options, cap, and the asking agent.\n * @returns the parsed receipt of the paid call.\n */"
          }
        ],
        "types": [
          {
            "name": "Agent",
            "declaration": "export interface Agent {\n    readonly id: SessionId;\n    readonly options: AgentOptions;\n    readonly session: Session;\n    readonly inbox: Inbox;\n    readonly status: AgentStatus;\n    readonly ctx: Context;\n    cancel(cause: AgentCancelCause, options?: CancelOptions): void;\n    whenIdle(): Promise<void>;\n    runMaintenance<T>(task: (signal: AbortSignal) => Promise<T>): Promise<T>;\n    send(message: UserMessage, target: InboxTarget, wakeup: boolean): void;\n    followup(message: UserMessage): void;\n    steer(message: UserMessage): void;\n    inject(message: UserMessage): void;\n}"
          },
          {
            "name": "AgentCancelCause",
            "declaration": "export type AgentCancelCause = { readonly kind: 'user'; } | { readonly kind: 'parent'; } | { readonly kind: 'hook'; readonly reason: string; } | { readonly kind: 'disposed'; };"
          },
          {
            "name": "AgentOptions",
            "declaration": "export interface AgentOptions {\n    provider?: string;\n    model?: string;\n    maxTokens?: number;\n}"
          },
          {
            "name": "AgentStatus",
            "declaration": "export type AgentStatus = 'idle' | 'running';"
          },
          {
            "name": "ApprovalOutcome",
            "declaration": "export type ApprovalOutcome = 'allowed-once' | 'rejected' | 'cancelled' | 'unavailable';"
          },
          {
            "name": "ApprovalPolicy",
            "declaration": "export type ApprovalPolicy = 'ask' | 'never';"
          },
          {
            "name": "ApprovalRequestId",
            "declaration": "export type ApprovalRequestId = Branded<'ApprovalRequestId'>;"
          },
          {
            "name": "AssistantMessage",
            "declaration": "export interface AssistantMessage extends Message {\n    readonly role: 'assistant';\n    readonly source: ModelMessageSource;\n}"
          },
          {
            "name": "AssistantProvenance",
            "declaration": "export interface AssistantProvenance {\n    provider: string;\n    model: string;\n    replayState?: unknown;\n}"
          },
          {
            "name": "AttachmentId",
            "declaration": "export type AttachmentId = Branded<'AttachmentId'>;"
          },
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "CallId",
            "declaration": "export type CallId = Branded<'CallId'>;"
          },
          {
            "name": "CancelOptions",
            "declaration": "export interface CancelOptions {\n    keepInbox?: boolean | undefined;\n}"
          },
          {
            "name": "CodeDispatchEventData",
            "declaration": "export interface CodeDispatchEventData extends CodeDispatchStartEventData {\n    isError: boolean;\n    content: ContentBlock[];\n}"
          },
          {
            "name": "CodeDispatchStartEventData",
            "declaration": "export interface CodeDispatchStartEventData {\n    rootCallId: CallId;\n    parentCallId: CallId;\n    subCallId: CallId;\n    name: string;\n    arguments: unknown;\n}"
          },
          {
            "name": "CommandId",
            "declaration": "export type CommandId = Branded<'CommandId'>;"
          },
          {
            "name": "CommandSource",
            "declaration": "export type CommandSource = CommandSourceMap[keyof CommandSourceMap];"
          },
          {
            "name": "CommandSourceMap",
            "declaration": "export interface CommandSourceMap {\n    user: { kind: 'user'; };\n}"
          },
          {
            "name": "ContentBlock",
            "declaration": "export type ContentBlock = ContentBlockMap[ContentBlockType];"
          },
          {
            "name": "ContentBlockMap",
            "declaration": "export interface ContentBlockMap {\n    text: TextBlock;\n    reasoning: ReasoningBlock;\n    image: ImageBlock;\n    'tool-call': ToolCallBlock;\n    'tool-result': ToolResultBlock;\n}"
          },
          {
            "name": "ContentBlockType",
            "declaration": "export type ContentBlockType = keyof ContentBlockMap;"
          },
          {
            "name": "ContextFormed",
            "declaration": "export type ContextFormed = { readonly form?: never; } | { readonly form: 'instructions'; } | { readonly form: 'catalog'; } | { readonly form: 'snapshot'; readonly sections: readonly ContextSnapshotSection[]; } | { readonly form: 'notice'; readonly summary: string; } | { readonly form: 'relay'; } | { readonly form: 'recall'; };"
          },
          {
            "name": "ContextSnapshotSection",
            "declaration": "export interface ContextSnapshotSection {\n    readonly name: string;\n    readonly text: string;\n}"
          },
          {
            "name": "EpochHeader",
            "declaration": "export interface EpochHeader {\n    config: LlmCallConfig;\n    adapterDefaults?: LlmCallConfigAdapterDefaults;\n    system?: string;\n    tools?: ToolSchema[];\n}"
          },
          {
            "name": "FinishReason",
            "declaration": "export type FinishReason = FinishReasonMap[keyof FinishReasonMap];"
          },
          {
            "name": "FinishReasonMap",
            "declaration": "export interface FinishReasonMap {\n    stop: { kind: 'stop'; };\n    'tool-calls': { kind: 'tool-calls'; };\n    'max-tokens': { kind: 'max-tokens'; };\n    aborted: { kind: 'aborted'; failure: LlmFailure; };\n    error: { kind: 'error'; failure: LlmFailure; };\n}"
          },
          {
            "name": "GoalBlockReason",
            "declaration": "export interface GoalBlockReason {\n    readonly code: string;\n    readonly message: string;\n}"
          },
          {
            "name": "GoalChangeMeta",
            "declaration": "export type GoalChangeMeta = GoalSnapshotChangeMeta | GoalClearChangeMeta;"
          },
          {
            "name": "GoalClearChangeMeta",
            "declaration": "export interface GoalClearChangeMeta {\n    readonly kind: 'goal/change';\n    readonly version: 1;\n    readonly operation: 'clear';\n    readonly cleared: GoalRef;\n    readonly clearedAt: number;\n}"
          },
          {
            "name": "GoalId",
            "declaration": "export type GoalId = Branded<'GoalId'>;"
          },
          {
            "name": "GoalMessageSource",
            "declaration": "export interface GoalMessageSource {\n    readonly kind: 'goal';\n    readonly goalId: GoalId;\n    readonly revision: number;\n    readonly round: number;\n}"
          },
          {
            "name": "GoalOperation",
            "declaration": "export type GoalOperation = 'create' | 'edit' | 'pause' | 'resume' | 'complete' | 'block' | 'clear';"
          },
          {
            "name": "GoalPhase",
            "declaration": "export type GoalPhase = 'active' | 'paused' | 'blocked' | 'complete';"
          },
          {
            "name": "GoalRef",
            "declaration": "export interface GoalRef {\n    readonly id: GoalId;\n    readonly revision: number;\n}"
          },
          {
            "name": "GoalSnapshot",
            "declaration": "export interface GoalSnapshot extends GoalRef {\n    readonly objective: string;\n    readonly phase: GoalPhase;\n    readonly blockedReason?: GoalBlockReason;\n    readonly maxGoalRounds: number;\n}"
          },
          {
            "name": "GoalSnapshotChangeMeta",
            "declaration": "export interface GoalSnapshotChangeMeta {\n    readonly kind: 'goal/change';\n    readonly version: 1;\n    readonly operation: Exclude<GoalOperation, 'clear'>;\n    readonly goal: GoalSnapshot;\n    readonly roundsStarted: number;\n    readonly createdAt: number;\n    readonly updatedAt: number;\n}"
          },
          {
            "name": "ImageAttachmentRef",
            "declaration": "export interface ImageAttachmentRef {\n    attachmentId: AttachmentId;\n    mediaType: ImageMediaType;\n    bytes: number;\n    width: number;\n    height: number;\n    name?: string;\n}"
          },
          {
            "name": "ImageBlock",
            "declaration": "export interface ImageBlock {\n    type: 'image';\n    attachment: ImageAttachmentRef;\n}"
          },
          {
            "name": "ImageMediaType",
            "declaration": "export type ImageMediaType = 'image/png' | 'image/jpeg' | 'image/webp' | 'image/gif';"
          },
          {
            "name": "Inbox",
            "declaration": "export class Inbox {\n    get nextTurn(): readonly UserMessage[];\n    get nextStep(): readonly UserMessage[];\n    get hasPending(): boolean;\n    clear(): void;\n    claim(target: InboxTarget, turn: number): UserMessage[];\n    append(target: InboxTarget, message: UserMessage): void;\n    prepend(target: InboxTarget, message: UserMessage): void;\n    replace(messageId: MessageId, newMessage: UserMessage): boolean;\n    remove(messageId: MessageId): boolean;\n    splice(target: InboxTarget, start: number, deleteCount: number, inserted: UserMessage[]): UserMessage[];\n}"
          },
          {
            "name": "InboxTarget",
            "declaration": "export type InboxTarget = 'next-turn' | 'next-step';"
          },
          {
            "name": "JsonValue",
            "declaration": "export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue; };"
          },
          {
            "name": "LlmCallConfig",
            "declaration": "export interface LlmCallConfig {\n    provider: string;\n    model: string;\n    reasoningEffort?: ReasoningEffortId;\n    temperature?: number;\n    maxTokens?: number;\n    stop?: string[];\n}"
          },
          {
            "name": "LlmCallConfigAdapterDefaults",
            "declaration": "export interface LlmCallConfigAdapterDefaults {\n    reasoningEffort?: true;\n    maxTokens?: true;\n}"
          },
          {
            "name": "LlmFailure",
            "declaration": "export interface LlmFailure {\n    readonly message: string;\n    readonly code: string;\n    readonly status?: number;\n    readonly providerRetryAfterMs?: number;\n    readonly requestId?: ProviderRequestId;\n}"
          },
          {
            "name": "Message",
            "declaration": "export interface Message {\n    readonly id: MessageId;\n    readonly role: 'system' | 'user' | 'assistant';\n    readonly content: ContentBlock[];\n    readonly source: MessageSource;\n}"
          },
          {
            "name": "MessageId",
            "declaration": "export type MessageId = Branded<'MessageId'>;"
          },
          {
            "name": "MessageSource",
            "declaration": "export type MessageSource = MessageSourceMap[keyof MessageSourceMap];"
          },
          {
            "name": "MessageSourceMap",
            "declaration": "export interface MessageSourceMap {\n    user: { kind: 'user'; };\n    plugin: { kind: 'plugin'; plugin: string; } & ContextFormed;\n    model: ModelMessageSource;\n    tool: ToolMessageSource;\n    goal: GoalMessageSource;\n}"
          },
          {
            "name": "ModelMessageSource",
            "declaration": "export interface ModelMessageSource extends AssistantProvenance {\n    kind: 'model';\n}"
          },
          {
            "name": "ProviderRequestId",
            "declaration": "export type ProviderRequestId = Branded<'ProviderRequestId'>;"
          },
          {
            "name": "ReasoningBlock",
            "declaration": "export interface ReasoningBlock {\n    type: 'reasoning';\n    text: string;\n}"
          },
          {
            "name": "ReasoningEffortId",
            "declaration": "export type ReasoningEffortId = Branded<'ReasoningEffortId'>;"
          },
          {
            "name": "RequestContext",
            "declaration": "export interface RequestContext {\n    provider: string;\n    model: string;\n    contextWindow?: number;\n}"
          },
          {
            "name": "RequestHeaderReason",
            "declaration": "export type RequestHeaderReason = 'initial' | 'resume' | 'change';"
          },
          {
            "name": "Session",
            "declaration": "export class Session {\n    get surface(): SessionSurface;\n    readonly header: SessionHeader;\n    get id(): SessionId;\n    readonly firstLiveSeq: number;\n    get events(): readonly SessionEvent[];\n    get seq(): number;\n    append<T extends SessionEventType>(type: T, data: SessionEventMap[T], ...opts: T extends SurfaceEventType ? [opts: SurfaceIntent] : []): SessionEvent<T>;\n    requestHeader(): EpochHeader | undefined;\n    requestContext(): RequestContext | undefined;\n    deriveMessages(): Message[];\n    deriveEventMessage(event: SessionEvent): Message | null;\n}"
          },
          {
            "name": "SessionEvent",
            "declaration": "export type SessionEvent<T extends SessionEventType = SessionEventType> = { [K in SessionEventType]: { type: K; seq: number; time: number; data: SessionEventMap[K]; ignorable?: true; } & (K extends SurfaceEventType ? { sourceEventSeqs?: number[]; surfaceOp?: SurfaceOp; } : object) }[T];"
          },
          {
            "name": "SessionEventMap",
            "declaration": "export interface SessionEventMap {\n    'turn/start': { turn: number; };\n    'turn/end': { turn: number; reason: TurnEndReason; };\n    'step/start': { turn: number; step: number; };\n    'step/end': { turn: number; step: number; };\n    'user/message': UserMessage;\n    'assistant/chunk': { turn: number; step: number; chunk: StreamChunk; };\n    'assistant/message': { turn: number; step: number; message: AssistantMessage; usage?: TokenUsage; };\n    'tool/call': { turn: number; step: number; callId: CallId; name: string; arguments: string; };\n    'tool/result': { turn: number; step: number; message: ToolResultMessage; error?: { name: string; code: string; }; meta?: JsonValue; };\n    'todo/write': { todos: TodoItem[]; };\n    'request/header': { header: EpochHeader; reason: RequestHeaderReason; };\n    'request/context': RequestContext;\n    'session/end-seed': Record<string, never>;\n    'agent/inbox/spliced': { target: InboxTarget; start: number; removedCount?: number; inserted: UserMessage[]; outcome?: 'canceled'; };\n    'command/run': { commandId: CommandId; name: string; args?: string; source: CommandSource; };\n    'command/done': { commandId: CommandId; kind: 'success' | 'error'; text?: string; sourceEventSeq?: number; };\n    'approval/asked': { id: ApprovalRequestId; toolName: string; callId?: CallId; reason?: string; };\n    'approval/decided': { id: ApprovalRequestId; outcome: ApprovalOutcome; };\n    'approval/policy': { policy: ApprovalPolicy; source?: 'delegation'; };\n    'tool/code-dispatch-start': CodeDispatchStartEventData;\n    'tool/code-dispatch': CodeDispatchEventData;\n    'goal/change': GoalChangeMeta;\n}"
          },
          {
            "name": "SessionEventType",
            "declaration": "export type SessionEventType = keyof SessionEventMap;"
          },
          {
            "name": "SessionHeader",
            "declaration": "export interface SessionHeader {\n    readonly version: number;\n    readonly id: SessionId;\n    readonly createdAt: number;\n    readonly cwd?: string;\n    readonly parentSession?: SessionId;\n    readonly seedLength?: number;\n    readonly origin?: 'subagent';\n    readonly delegationDepth?: number;\n    readonly agentPreset?: string;\n}"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          },
          {
            "name": "SessionSurface",
            "declaration": "export interface SessionSurface {\n    readonly nodes: readonly number[];\n    readonly replaceGeneration: number;\n}"
          },
          {
            "name": "StreamChunk",
            "declaration": "export type StreamChunk = { type: 'block-start'; index: number; blockType: ContentBlockType; } | { type: 'text-delta'; index: number; text: string; } | { type: 'reasoning-delta'; index: number; text: string; } | { type: 'tool-call-delta'; index: number; id: CallId; name?: string; argumentsDelta: string; } | { type: 'block-end'; index: number; block: ContentBlock; } | { type: 'usage'; usage: TokenUsage; } | { type: 'finish'; reason: FinishReason; replayState?: unknown; };"
          },
          {
            "name": "SurfaceEventType",
            "declaration": "export type SurfaceEventType = 'user/message' | 'assistant/message' | 'tool/result';"
          },
          {
            "name": "SurfaceIntent",
            "declaration": "export interface SurfaceIntent {\n    surfaceOp: SurfaceOp;\n    sourceEventSeqs?: number[];\n}"
          },
          {
            "name": "SurfaceOp",
            "declaration": "export type SurfaceOp = 'append' | { op: 'replace'; start: number; end: number; };"
          },
          {
            "name": "TextBlock",
            "declaration": "export interface TextBlock {\n    type: 'text';\n    text: string;\n}"
          },
          {
            "name": "TodoItem",
            "declaration": "export interface TodoItem {\n    content: string;\n    status: 'pending' | 'in_progress' | 'completed';\n}"
          },
          {
            "name": "TokenUsage",
            "declaration": "export interface TokenUsage {\n    inputTokens: number;\n    outputTokens: number;\n    cacheReadTokens?: number;\n    cacheWriteTokens?: number;\n    reasoningTokens?: number;\n}"
          },
          {
            "name": "ToolCallBlock",
            "declaration": "export interface ToolCallBlock {\n    type: 'tool-call';\n    id: CallId;\n    name: string;\n    arguments: string;\n}"
          },
          {
            "name": "ToolMessageSource",
            "declaration": "export interface ToolMessageSource {\n    kind: 'tool';\n    callId: CallId;\n}"
          },
          {
            "name": "ToolResultBlock",
            "declaration": "export interface ToolResultBlock {\n    type: 'tool-result';\n    toolCallId: CallId;\n    content: ContentBlock[];\n    isError?: boolean;\n}"
          },
          {
            "name": "ToolResultMessage",
            "declaration": "export interface ToolResultMessage extends Message {\n    readonly role: 'user';\n    readonly content: [ToolResultBlock];\n    readonly source: ToolMessageSource;\n}"
          },
          {
            "name": "ToolSchema",
            "declaration": "export interface ToolSchema {\n    name: string;\n    description: string;\n    parameters: Record<string, unknown>;\n}"
          },
          {
            "name": "TurnEndCancelCause",
            "declaration": "export type TurnEndCancelCause = AgentCancelCause | { readonly kind: 'legacy'; };"
          },
          {
            "name": "TurnEndReason",
            "declaration": "export type TurnEndReason = TurnEndReasonMap[keyof TurnEndReasonMap];"
          },
          {
            "name": "TurnEndReasonMap",
            "declaration": "export interface TurnEndReasonMap {\n    completed: { kind: 'completed'; };\n    aborted: { kind: 'aborted'; reason: TurnEndCancelCause; };\n    blocked: { kind: 'blocked'; };\n    error: { kind: 'error'; error: LlmFailure; };\n    'max-tokens': { kind: 'max-tokens'; };\n    interrupted: { kind: 'interrupted'; };\n}"
          },
          {
            "name": "UserMessage",
            "declaration": "export interface UserMessage extends Message {\n    readonly role: 'user';\n}"
          },
          {
            "name": "X402CatalogEntry",
            "declaration": "export interface X402CatalogEntry {\n    resource: string;\n    description: string;\n    network: string;\n    priceUsdc: string;\n    scheme: string;\n    x402Version: number;\n    live: boolean;\n}"
          },
          {
            "name": "X402EstimateResult",
            "declaration": "export type X402EstimateResult = { requiresPayment: false; status: number; } | { requiresPayment: true; requirement: X402PaymentRequirement; };"
          },
          {
            "name": "X402HistoryEntry",
            "declaration": "export interface X402HistoryEntry {\n    hash: string;\n    from: string;\n    to: string;\n    amountUsdc: string;\n    blockNumber: number;\n    direction: 'out' | 'in';\n}"
          },
          {
            "name": "X402PaymentReceipt",
            "declaration": "export interface X402PaymentReceipt {\n    url: string;\n    status: number;\n    paymentStatus: 'settled' | 'settle_failed' | 'payment_required' | 'none';\n    body: JsonValue;\n    transaction?: string;\n    payer?: string;\n}"
          },
          {
            "name": "X402PaymentRecord",
            "declaration": "export interface X402PaymentRecord {\n    id: string;\n    url: string;\n    amountUsdc: string;\n    network: string;\n    transaction?: string;\n    status: 'settled' | 'failed';\n    time: number;\n}"
          },
          {
            "name": "X402PaymentRequirement",
            "declaration": "export interface X402PaymentRequirement {\n    scheme: string;\n    network: string;\n    amountRaw: string;\n    amountUsdc: string;\n    resource: string;\n    description: string;\n    payTo: string;\n    maxTimeoutSeconds: number;\n}"
          },
          {
            "name": "X402PayToolArgs",
            "declaration": "export interface X402PayToolArgs {\n    url: string;\n    maxCostUsdc?: number | undefined;\n    method?: string | undefined;\n    headers?: Record<string, string> | undefined;\n    body?: JsonValue | undefined;\n}"
          },
          {
            "name": "X402SendReceipt",
            "declaration": "export interface X402SendReceipt {\n    transaction: string;\n    to: string;\n    amountUsdc: string;\n    status: 'confirmed';\n}"
          },
          {
            "name": "X402WalletRecord",
            "declaration": "export interface X402WalletRecord {\n    id: string;\n    label: string;\n    address: string;\n    isCurrent: boolean;\n}"
          },
          {
            "name": "X402WalletState",
            "declaration": "export interface X402WalletState {\n    configured: boolean;\n    address?: string;\n    usdcBalance?: string;\n    network: string;\n    label?: string;\n    walletId?: string;\n}"
          }
        ]
      }
    ],
    "events": [
      {
        "description": "One paid x402 call settled or failed; the GUI popup replays from this.",
        "summary": "One paid x402 call settled or failed; the GUI popup replays from this.",
        "tags": [
          {
            "name": "param",
            "argument": "payment",
            "comment": "- URL, amount, network, transaction, and outcome.",
            "text": "@param payment - URL, amount, network, transaction, and outcome.\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * One paid x402 call settled or failed; the GUI popup replays from this.\n * @param payment - URL, amount, network, transaction, and outcome.\n * @mode emit\n */",
        "name": "x402/payment",
        "mode": "emit",
        "signature": "'x402/payment'(payment: X402PaymentRecord): void"
      }
    ],
    "objects": []
  },
}
