/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { X402HistoryEntry, X402PaymentRecord, X402SendReceipt, X402WalletRecord, X402WalletState } from '@deepseek-ai/dsh-x402/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$78343032 {
    createWallet: (request: { label: string; privateKey?: string; }) => Promise<RemoteResult<X402WalletRecord>>
    history: (limit?: number) => Promise<RemoteResult<X402HistoryEntry[]>>
    payments: () => Promise<RemoteResult<X402PaymentRecord[]>>
    selectWallet: (id: string) => Promise<RemoteResult<{ ok: true; }>>
    send: (request: { to: string; amountUsdc: string; }) => Promise<RemoteResult<X402SendReceipt>>
    wallet: () => Promise<RemoteResult<X402WalletState>>
    wallets: () => Promise<RemoteResult<X402WalletRecord[]>>
  }
  interface TypertRemoteMap {
    'x402/createWallet': (request: { label: string; privateKey?: string; }) => Promise<RemoteResult<X402WalletRecord>>
    'x402/history': (limit?: number) => Promise<RemoteResult<X402HistoryEntry[]>>
    'x402/payments': () => Promise<RemoteResult<X402PaymentRecord[]>>
    'x402/selectWallet': (id: string) => Promise<RemoteResult<{ ok: true; }>>
    'x402/send': (request: { to: string; amountUsdc: string; }) => Promise<RemoteResult<X402SendReceipt>>
    'x402/wallet': () => Promise<RemoteResult<X402WalletState>>
    'x402/wallets': () => Promise<RemoteResult<X402WalletRecord[]>>
  }
  interface TypertRemoteNamespaceMap {
    'x402': TypertRemoteNamespace$78343032
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
